name: Build and Test
on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'
jobs:
    build-test:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.13.0
            - name: Install dependencies
              run: yarn install
            - name: Lint Code
              run: yarn lint
            - name: Build and Compile Typescript
              run: yarn build
            - name: Run test cases
              run: yarn test --watchAll=false