name: Deploy to Staging Environment
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
jobs:
  Deploy-Staging:
    if: |
      github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build and Compile Typescript
        run: yarn build
      - name: Deploy to Heroku Staging Environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'govbot-test'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_DISCORD_BOT_ACTIVITY: ${{vars.DISCORD_BOT_ACTIVITY}}
          HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.QA_DISCORD_BOT_APPLICATION_ID}}
          HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.QA_DISCORD_BOT_PUBLIC_KEY}}
          HD_DISCORD_BOT_TOKEN: ${{secrets.QA_DISCORD_BOT_TOKEN}}
          HD_GOVERNATOR_API_BASE_PATH: ${{vars.QA_GOVERNATOR_API_BASE_PATH}}
          HD_GOVERNATOR_API_ENDPOINT_SSE: ${{vars.GOVERNATOR_API_ENDPOINT_SSE}}
          HD_GOVERNATOR_API_KEY: ${{secrets.QA_GOVERNATOR_API_KEY}}
          HD_GOVERNATOR_API_PREFIX: ${{vars.GOVERNATOR_API_GLOBAL_PREFIX}}
          HD_GOVERNATOR_LOGO_URL: ${{vars.GOVERNATOR_LOGO_URL}}
          HD_LOG_LEVEL: ${{vars.QA_LOG_LEVEL}}
          HD_YARN_PRODUCTION: ${{vars.QA_YARN_PRODUCTION}}






          